client_secret: UsC5sNDciSaNggxJdB3EGSGYS242VT7q
debug: false
disable_auto_update: true
disable_command_execute: false
disable_force_update: true
disable_nat: false
disable_send_query: false
gpu: false
insecure_tls: false
ip_report_period: 1800
report_delay: 4
server: nzku.fortymenty.eu.org:443
skip_connection_count: false
skip_procs_count: false
temperature: false
tls: true
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: 05e06048-0e91-4561-924d-ed67a168bbbb
